### PR TITLE
Login fixing

### LINKED ISSUE #266: Login does not allow to save credentials in browser
I'd personally like to store my credentials in Firefox' credential store, but the way ldjam's login is done, does not trigger Firefox' "Save credentials" popup.

### PR DESCRIPTION
**Pull request by local-minimum**
Resolves #266 #1501 

ld_login

* Can now save login+password pairs in Firefox, Chrome and probably Safari.
* The autofill works in Firefox and Chrome when using mouse and/or keyboard to select stored login
* Can now submit form from both input-fields, not just the password field.

### CODE REVIEW

**Comment by mikekasprzak** [comment]
This PR has extra files. I'm assuming they come from #1563.

**Comment by local-minimum** [comment]
Oh I messed up my master. Yes they would come from the embeds thing

**Comment by local-minimum** [comment]
Do you want me to fix or will you merge that PR and then it won't matter (hopefully)

**Comment by local-minimum** [comment]
I'm just gonna close these PR since they've grown very old and it's annoying to see them in my open PR listing. If there's another bout of dev on the site and you want more help, let me know.

**Comment by local-minimum** [comment]
@mikekasprzak, I closed this a long time ago because having open PRs annoyed me but it is possible it still is useful. If not, please close it again. Also great that there's going to be dev on the site again!

I'm not sure about this one, it might be duplicated, at least in part by the two other login-PRs

**Pull request closed without merging**
